apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-amf
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open5gs-amf
  template:
    metadata:
      labels:
        app: open5gs-amf
    spec:
      nodeSelector:
        leistung: niedrig
      initContainers:
        - name: create-log-dir
          image: busybox
          command: ["mkdir", "-p", "/open5gs/install/var/log/open5gs"]
          volumeMounts:
            - name: log-dir
              mountPath: /open5gs/install/var/log/open5gs
      containers:
        - name: amf
          image: ghcr.io/borjis131/amf:v2.7.5
          ports:
            - containerPort: 7777
            - containerPort: 38412
          volumeMounts:
            - name: log-dir
              mountPath: /open5gs/install/var/log/open5gs
      volumes:
        - name: log-dir
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: open5gs-amf
  namespace: open5gs
spec:
  selector:
    app: open5gs-amf
  ports:
    - name: sbi
      port: 7777
    - name: ngap
      port: 38412
      protocol: SCTP
