apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-nrf
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open5gs-nrf
  template:
    metadata:
      labels:
        app: open5gs-nrf
    spec:
      nodeSelector:
        leistung: hoch
      initContainers:
        - name: create-log-dir
          image: busybox
          command: ["mkdir", "-p", "/open5gs/install/var/log/open5gs"]
          volumeMounts:
            - name: log-dir
              mountPath: /open5gs/install/var/log/open5gs
      containers:
        - name: nrf
          image: ghcr.io/borjis131/nrf:v2.7.5
          ports:
            - containerPort: 7777
          volumeMounts:
            - name: log-dir
              mountPath: /open5gs/install/var/log/open5gs
      volumes:
        - name: log-dir
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: open5gs-nrf
  namespace: open5gs
spec:
  selector:
    app: open5gs-nrf
  ports:
    - port: 7777
